## **Imports**

In [1]:
import os
import pandas as pd

## **Variables generals**

In [2]:
dies_mes = {
    "Enero": 31,
    "Febrero": 28,
    "Marzo": 31,
    "Abril": 30,
    "Mayo": 31,
    "Junio": 30,
    "Julio": 31,
    "Agosto": 31,
    "Septiembre": 30,
    "Octubre": 31, 
    "Noviembre": 30,
    "Diciembre": 31
}

## **Carregar dataset**

In [3]:
dataset_dir = "../01_dades/brut/"
save_dir = "../01_dades/processat/"

dataset_nom = "IDVFC_NM_dic25.csv"

In [4]:
# Carregar dataset
df_path = os.path.join(dataset_dir, dataset_nom)
df = pd.read_csv(df_path, encoding="latin-1")

# Filtrar per tipus d'homicidi
df_hd = df[(df["Subtipo de delito"] == "Homicidio doloso")]

# Eliminar columnes d'informació addicional
df_hd.drop(columns = ["Clave_Ent", "Entidad", "Bien jurídico afectado", "Tipo de delito", "Subtipo de delito", "Modalidad", "Sexo", "Rango de edad"], inplace=True)

### **Filtre semestral**

In [5]:
primer_semestre = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio"]

# Eliminar columnes juny-desembre
df_hd_sem = df_hd[["Año"] + primer_semestre]

#### **Frecuencia absoluta**

In [6]:
# Agrupar per any
df_hd_sem = df_hd_sem.groupby("Año").sum()
df_hd_sem.head()

      Enero  Febrero  Marzo  Abril  Mayo  Junio
Año
2015   1354     1388   1379   1442  1601   1466
2016   1532     1590   1707   1649  1878   1782
2017   2136     2077   2202   2183  2420   2506
2018   2568     2445   2790   2775  2937   2768
2019   2874     2824   2877   2750  2914   3004

In [7]:
# Guardar conteig absolut per any i mes
df_hd_sem.to_csv(os.path.join(save_dir, "homicidio_doloso_semestral_frecuencia_absoluta.csv"))

#### **Promig diari**

In [8]:
# Calcular promig diari
df_hd_sem_prom = df_hd_sem.copy()

for mes in primer_semestre:
    df_hd_sem_prom[mes] = df_hd_sem[mes] / dies_mes[mes]

df_hd_sem_prom.head()

          Enero     Febrero      Marzo      Abril       Mayo       Junio
Año
2015  43.677419   49.571429  44.483871  48.066667  51.645161   48.866667
2016  49.419355   56.785714  55.064516  54.966667  60.580645   59.400000
2017  68.903226   74.178571  71.032258  72.766667  78.064516   83.533333
2018  82.838710   87.321429  90.000000  92.500000  94.741935   92.266667
2019  92.709677  100.857143  92.806452  91.666667  94.000000  100.133333

In [9]:
# Guardar promig diari per any i mes
df_hd_sem_prom.to_csv(os.path.join(save_dir, "homicidio_doloso_semestral_promedio_diario.csv"))

### **Filtre mensual (Juliol)**

In [10]:
mes = "Julio"

# Eliminar totes les columnes menys juliol
df_hd_mes = df_hd[["Año", mes]]

#### **Frecuencia absoluta**

In [11]:
# Agrupar per any
df_hd_mes = df_hd_mes.groupby("Año").sum()
df_hd_mes.head()

      Julio
Año
2015   1539
2016   2074
2017   2402
2018   3074
2019   2981

In [12]:
# Guardar conteig absolut per any i mes
df_hd_mes.to_csv(os.path.join(save_dir, f"homicidio_doloso_{mes}_frecuencia_absoluta.csv"))

#### **Promig diari**

In [13]:
# Calcular promig diari
df_hd_sem_prom = df_hd_mes.copy()
df_hd_sem_prom[mes] = df_hd_mes[mes] / dies_mes[mes]
df_hd_sem_prom.head()

          Julio
Año
2015  49.645161
2016  66.903226
2017  77.483871
2018  99.161290
2019  96.161290

In [14]:
# Guardar promig diari per any i mes
df_hd_sem_prom.to_csv(os.path.join(save_dir, f"homicidio_doloso_{mes}_promedio_diario.csv"))